local theme = require("modules.base16").get_theme_table("base16")

return {
  DevIconDefault = { fg = theme.base08 },
  DevIconc = { fg = theme.base0D },
  DevIconcss = { fg = theme.base0D },
  DevIcondeb = { fg = theme.base0C },
  DevIconDockerfile = { fg = theme.base0C },
  DevIconhtml = { fg = theme.base0F },
  DevIconjpeg = { fg = theme.base0E},
  DevIconjpg = { fg = theme.base0E },
  DevIconjs = { fg = theme.base09 },
  DevIconkt = { fg = theme.base09 },
  DevIconlock = { fg = theme.base08 },
  DevIconlua = { fg = theme.base0D },
  DevIconmp3 = { fg = theme.base07 },
  DevIconmp4 = { fg = theme.base07 },
  DevIconout = { fg = theme.base07 },
  DevIconpng = { fg = theme.base0E },
  DevIconpy = { fg = theme.base0C },
  DevIcontoml = { fg = theme.base0D },
  DevIconts = { fg = theme.base0C },
  DevIconttf = { fg = theme.base07 },
  DevIconrb = { fg = theme.base0F },
  DevIconrpm = { fg = theme.base09 },
  DevIconvue = { fg = theme.base0B },
  DevIconwoff = { fg = theme.base07 },
  DevIconwoff2 = { fg = theme.base07 },
  DevIconxz = { fg = theme.base09 },
  DevIconzip = { fg = theme.base09 },
  DevIconZig = { fg = theme.base09 },
  DevIconMd = {fg = theme.base0D },
  DevIconTSX = {fg = theme.base0D },
  DevIconJSX = {fg = theme.base0D },
  DevIconSvelte = {fg = theme.base08 },
  DevIconJava = {fg = theme.base09 },
  DevIconDart = {fg = theme.base0C }
}
